### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by h3ckphy** [nexquery/samp-textdraw-streamer#4]
Selam, kardesim.
Can you please rename your functions according to original samp functions? Like CreatePlayerTextDraw, PlayerTextDrawDestroy etc?
Also I'd like to see some extra ids in textdraws that can be used in some cases like in this include https://github.com/kristoisberg/samp-td-streamer.
For example, I'm developing PlayerTextDrawFade function and I need to hold textdraw's state if it's fading now or not. I could do something like PlayerTextDrawExtra1(playerid, playertextid, value).

**Comment by nexquery** [comment]
Selam, kardesim.

Since some functions have long names, the names of natives have been shortened. Because I was using the ALS method, the names were reaching the 31 character limit and there was an error in compilation. But you can use Original functions. So you can create textdraw with CreatePlayerTextDraw and delete textdraw with PlayerTextDrawDestroy. No need to use CreatePTextdraw and DestroyPTextdraw :)

As for your second suggestion, I think you want to store a value in textdraw and get it back.

**So like this:**
PlayerTextDrawExtra(playerid, PlayerText:text, value);
PlayerTextDrawGetExtra(playerid, PlayerText:text, &value);

I hope I understood your suggestion properly.

**Comment by h3ckphy** [comment]
Oh, I didn't know that. Thank you.

Yes, you right.
For example, in streamer by Incognito for objects, pickups or whatever, there are extra IDs that can be used by developers to hold some values.

**Comment by nexquery** [comment]
I will add the feature you want soon.

**Comment by h3ckphy** [comment]
Thanks, bro.

Also I wanted to ask you something, because I barely know C++. How is your streamer implemented?
Do you just destroy textdraws that is not shown on the screen? And then recreate it when PlayerTextDrawShow() called?

**Comment by nexquery** [comment]
When PlayerTextdrawHide is used, the existing textdraw is completely removed, so the PlayerTextdrawDestroy action is applied.  Textdraw is recreated with CreatePlayerTextdraw when PlayerTextdrawShow is used. In this way, the textdraw limit is exceeded.

**Comment by nexquery** [comment]
Hello again, the feature you requested has been added.
[Click](https://github.com/nexquery/samp-textdraw-streamer/blob/085c532c103eabe1e09e8a3112f74668dbc10121/textdraw-streamer.inc#L67)

**Comment by h3ckphy** [comment]
Hi! That's awesome. I hope it's gonna be useful for someone else.
I guess issue can be closed. You're cool!
